### ISSUE TITLE
Small mistake in your paper

### ISSUE THREAD

**Issue by yinxiaochuan** [aimerykong/Pixel-Attentional-Gating#1]
Very interesting work!

I think  the Eq. (4) should be g=softmax((log(\alpha) + m)/\tau)

**Comment by aimerykong** [comment]
Hi, thanks for your catch, and apologize for such a delayed response!
You are right that Eq.(4) is not correct... but we implement it correctly:-)

https://github.com/aimerykong/Pixel-Attentional-Gating/blob/389a56a681e4c04e58ccd1117b0bd901f757f23d/demo1_Panoramic_Surface_Normal/scriptFolder/GumbelNoisySoftMax.m#L23

**Comment by yinxiaochuan** [comment]
Thank you for your response. Good work!
